# Generated by Django 5.2.3 on 2025-06-16 16:11

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_common', models.CharField(max_length=100, unique=True)),
                ('name_official', models.CharField(max_length=200)),
                ('capital', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None)),
                ('population', models.BigIntegerField()),
                ('area', models.FloatField()),
                ('languages', models.JSONField(default=dict)),
                ('region', models.CharField(blank=True, max_length=50)),
                ('subregion', models.CharField(blank=True, max_length=100)),
                ('currencies', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
